### ISSUE TITLE
TTF won't open with fontTools/ttx

### ISSUE THREAD

**Issue by davelab6** [typeoff/martel#1]
How did you generate these TTFs? They won't open with fontTools/ttx :) 

```
$ ttx Martel-Bold.ttf;
Dumping "Martel-Bold.ttf" to "Martel-Bold.ttx"...
Dumping 'GlyphOrder' table...
An exception occurred during the decompilation of the 'post' table
Traceback (most recent call last):
  File "/usr/local/bin/ttx", line 6, in <module>
    ttx.main(sys.argv[1:])
  File "/usr/local/lib/python2.7/site-packages/FontTools/fontTools/ttx.py", line 310, in main
    process(jobs, options)
  File "/usr/local/lib/python2.7/site-packages/FontTools/fontTools/ttx.py", line 295, in process
    action(input, output, options)
  File "/usr/local/lib/python2.7/site-packages/FontTools/fontTools/ttx.py", line 206, in ttDump
    bitmapGlyphDataFormat=options.bitmapGlyphDataFormat)
  File "/usr/local/lib/python2.7/site-packages/FontTools/fontTools/ttLib/__init__.py", line 283, in saveXML
    self._tableToXML(tableWriter, tag, progress, quiet)
  File "/usr/local/lib/python2.7/site-packages/FontTools/fontTools/ttLib/__init__.py", line 323, in _tableToXML
    table.toXML(writer, self)
  File "/usr/local/lib/python2.7/site-packages/FontTools/fontTools/ttLib/__init__.py", line 773, in toXML
    glyphOrder = ttFont.getGlyphOrder()
  File "/usr/local/lib/python2.7/site-packages/FontTools/fontTools/ttLib/__init__.py", line 443, in getGlyphOrder
    glyphOrder = self['post'].getGlyphOrder()
AttributeError: 'DefaultTable' object has no attribute 'getGlyphOrder'
$
```

**Comment by typeoff** [comment]
Dear Dave,

Hmmm, interesting! These TTFs are exported from the Glyphs 2.0 beta. I will try opening the TTFs in FontLab and exporting them again from there. Perhaps those will bypass this problem. 

Thanks,
Dan

**Comment by davelab6** [comment]
cc @schriftgestalt

**Comment by schriftgestalt** [comment]
Could you send me the .glyphs file and the .ttf?

**Comment by davelab6** [comment]
Download here, 

https://github.com/typeoff/martel/raw/master/Martel%20Source%20Files/Martel%20All%20Three%20Masters%2020141117%2001.glyphs

https://github.com/typeoff/martel/raw/master/Martel%20Font%20Files/Martel-Bold.ttf

**Comment by typeoff** [comment]
Yes, but remember that those TTFs have been run through ttfautohint after they came out of Glyphs.

Thanks,
Dan

**Comment by typeoff** [comment]
Ugh, this opening in FLS and exporting from there is not working so well. I have some glyph reordering going wrong, or something. I will keep trying.

Georg, Dave is right. The Glyphs file that I generated my TTFs from (before they went through ttfautoedit) are getable in the link above. If you can’t fetch them, though, I can e-mail you the package.

**Comment by schriftgestalt** [comment]
What version of Glyphs was used to write this .ttf? I tried it with the current version and it produces a correct file (that can be parsed by ttx). The problem number of glyphs in the maxp was wrong and thous the offset to the name strings was calculated incorrectly. Maybe remove the comparison tp the maxp table in the post table decompiler?

**Comment by davelab6** [comment]
ttfa doesn't usually stop ttx from working, I doubt it is related. Maybe
upload unhinted TTFs as well?

**Comment by typeoff** [comment]
Well, since the files that were on GitHubuntil a moment ago were created in early December, I don’t have the same version of the Glyphs 2 beta installed on my machine that I did when their generation happened. And I didn’t save un-ttfautohinted version. So I can’t recreate them.
But I have uploaded new files. I have updated Glyphs 2 to the newest version (as of last night) and regenerated the TTFs from that Glyphs file. I also made a new Glyphs file, because in early December, Glyphs could still interpolate from masters that did not have compatible anchors. Since this isn’t possible now, I fixed a few dozen glyphs – just in terms of anchors.
So now there are new TTF files here, in two versions. There are TTFs generated directly from the Glyphs 2.0.0 (688) beta, without any TT hints. 
Then there are TTF files that are those Glyphs TTFs, with ttfautohint applied. 
Each set of TTFs is available on Github in its own marked folder, as are both the old and new Glyphs source files.
Thanks,Dan

Date: Tue, 27 Jan 2015 07:23:00 -0800

**Comment by typeoff** [comment]
The files uploaded a moment ago as part of Version 1.001 are able to be opened with TTX. The TTF files in the repository that have been hinted with ttfautohint have been roundtrip through TTX to remove certain namerecord entries. This issue is now closed.
